### ISSUE TITLE
Home assistant logs says component is using deprecated or wrong implementation

### ISSUE THREAD

**Issue by AnderzL7** [dadge/awesome_thermostat#17]
## Version of the custom_component

Latest version (5th April)

## Configuration
Configuration is not really needed to get this error, but non the less:
```yaml

- platform: awesome_thermostat
  name: Sov temp
  heater: switch.panelovn_sov
  target_sensor: sensor.weighted_average_sov_temp
  min_temp: 14
  max_temp: 28
  cold_tolerance: 0.1
  hot_tolerance: 0.1

```

## Describe the bug
Home assistant logs, logs the 2 following warnings when starting. See logs below.

## Debug log
(Not debug log, but logs from Settings -> System -> Logs)

```text

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1597
First occurred: 19:33:37 (2 occurrences)
Last logged: 19:33:37

Entity None (<class 'custom_components.awesome_thermostat.climate.AwesomeThermostat'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE: 1>, please create a bug report at https://github.com/dadge/awesome_thermostat/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

---

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:361
integration: Climate (documentation, issues)
First occurred: 19:33:37 (2 occurrences)
Last logged: 19:33:37

Entity None (<class 'custom_components.awesome_thermostat.climate.AwesomeThermostat'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/dadge/awesome_thermostat/issues

```
